import { NextRequest, NextResponse } from "next/server";
import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";

import { prisma } from "@/lib/prisma";
import { buildKhazanahQuery } from "@/lib/khazanah/query";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    const keyword = searchParams.get("keyword") ?? "";
    const category = searchParams.get("category") ?? "";
    const status = searchParams.get("status") ?? "";
    const state = searchParams.get("state") ?? "";
    const year = searchParams.get("year") ?? "";
    const sort = searchParams.get("sort") ?? "";

    const { where, orderBy } = buildKhazanahQuery({
      keyword,
      category,
      status,
      state,
      year,
      sort,
    });

    const assets = await prisma.knowledgeAsset.findMany({
      where,
      orderBy,
    });

    const pdfDoc = await PDFDocument.create();

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let page = pdfDoc.addPage([595, 842]);

    const { width, height } = page.getSize();

    let y = height - 50;

    // ======================
    // Header
    // ======================

    page.drawText("SINAR", {
      x: 50,
      y,
      size: 22,
      font: bold,
    });

    y -= 28;

    page.drawText("Political Intelligence Platform", {
      x: 50,
      y,
      size: 12,
      font,
    });

    y -= 35;

    page.drawText("Khazanah Politik", {
      x: 50,
      y,
      size: 18,
      font: bold,
    });

    y -= 20;

    page.drawText("Laporan Dokumen", {
      x: 50,
      y,
      size: 12,
      font,
    });

    y -= 30;

    page.drawText(
      `Tarikh Jana : ${new Date().toLocaleString("ms-MY")}`,
      {
        x: 50,
        y,
        size: 10,
        font,
      }
    );

    y -= 15;

    page.drawText(`Jumlah Rekod : ${assets.length}`, {
      x: 50,
      y,
      size: 10,
      font,
    });

    if (category) {
      y -= 15;
      page.drawText(`Kategori : ${category}`, {
        x: 50,
        y,
        size: 10,
        font,
      });
    }

    if (state) {
      y -= 15;
      page.drawText(`Negeri : ${state}`, {
        x: 50,
        y,
        size: 10,
        font,
      });
    }

    if (status) {
      y -= 15;
      page.drawText(`Status : ${status}`, {
        x: 50,
        y,
        size: 10,
        font,
      });
    }

    if (year) {
      y -= 15;
      page.drawText(`Tahun : ${year}`, {
        x: 50,
        y,
        size: 10,
        font,
      });
    }

    if (keyword) {
      y -= 15;
      page.drawText(`Carian : ${keyword}`, {
        x: 50,
        y,
        size: 10,
        font,
      });
    }

    y -= 30;

    page.drawLine({
      start: { x: 50, y },
      end: { x: width - 50, y },
      thickness: 1,
      color: rgb(0.6, 0.6, 0.6),
    });

    y -= 20;

    // ======================
    // Senarai Rekod
    // ======================

    assets.forEach((asset, index) => {

      if (y < 80) {

        page = pdfDoc.addPage([595, 842]);

        y = height - 50;

      }

      page.drawText(
        `${index + 1}. ${asset.title}`,
        {
          x: 50,
          y,
          size: 11,
          font: bold,
        }
      );

      y -= 14;

      page.drawText(
        `Kategori: ${asset.category} | Negeri: ${asset.state ?? "-"} | Tahun: ${
          asset.year ?? "-"
        } | Status: ${asset.status}`,
        {
          x: 60,
          y,
          size: 9,
          font,
        }
      );

      y -= 12;

      if (asset.summary) {

        const summary =
          asset.summary.length > 180
            ? asset.summary.substring(0, 180) + "..."
            : asset.summary;

        page.drawText(summary, {
          x: 60,
          y,
          size: 8,
          font,
          maxWidth: 470,
          lineHeight: 10,
        });

        y -= 25;
      }

      y -= 10;

    });

    // ======================
    // Footer
    // ======================

    const pages = pdfDoc.getPages();

    pages.forEach((p, i) => {

      p.drawLine({
        start: { x: 50, y: 40 },
        end: { x: width - 50, y: 40 },
        thickness: 1,
        color: rgb(0.8, 0.8, 0.8),
      });

      p.drawText(
        `Generated by SINAR • Page ${i + 1} of ${pages.length}`,
        {
          x: 50,
          y: 20,
          size: 8,
          font,
        }
      );

    });

   const pdfBytes = await pdfDoc.save();

const body = pdfBytes.buffer.slice(
  pdfBytes.byteOffset,
  pdfBytes.byteOffset + pdfBytes.byteLength
) as ArrayBuffer;

return new Response(body, {
  headers: {
    "Content-Type": "application/pdf",
    "Content-Disposition":
      'attachment; filename="Khazanah_Politik.pdf"',
  },
});

  } catch (error) {

    console.error(error);

    return NextResponse.json(
      {
        success: false,
        message: "Export PDF gagal.",
      },
      {
        status: 500,
      }
    );

  }
}